title: "My Lifelong Learning"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# 添加这行来禁用 GitHub 按钮
github: false

navbar:
  - title: "首页"
    url: "/"
  - title: "关于"
    url: "/about.html"
  - title: "联系" 
    url: "/contact.html"
