title: "My Lifelong Learning"
remote_theme: pages-themes/midnight@v0.2.0  # 这个主题支持导航
plugins:
  - jekyll-remote-theme

navbar:
  - title: "首页"
    url: "/"
  - title: "关于"
    url: "/about.html"
  - title: "联系"
    url: "/contact.html"
